
* Trading Bot

** Setup



#+begin_src bash
python3 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
#+end_src

   
** Run

#+begin_src bash
python3 main.py
#+end_src

** What it does
- Uses the Pi42 API to fetch historical data for a specified symbol.
- Makes decisions based on mathematical metrics.
- Simulates trading based on the generated signals.

** How the Code Works

1. **Fetch Historical Data**: The code fetches historical data for the specified symbol ("BTCINR") from the Pi42 API.
2. **Calculate Mean and Standard Deviation**: It calculates the rolling mean and standard deviation of the closing prices over a 24-period window.
3. **Calculate Additional Metrics**: The code calculates additional metrics, such as returns, z-score, skewness, and kurtosis.
4. **Mean Reversion Strategy**: The strategy generates trading signals based on the mean reversion concept. If the closing price is below the mean minus the standard deviation, it generates a "buy" signal. If the closing price is above the mean plus the standard deviation, it generates a "sell" signal.
5. **Simulate Trading**: The code simulates trading based on the generated signals, calculating the profit/loss over the trading period.



*** TODO Replace Sell with % Risk Buy for Bullish Markest
